from __future__ import annotations
import itertools
import uuid
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from super_hard_card_game import SHCGGameState


# NOTE: every time modifying a card class and its subclass, remember to also modify ai_player_new.py's copy_card() function accordingly.
# Also, modify ai_player_new.py's _hash_game_state() function to include any new attributes that affect game state.

class Card:
    def __init__(self, name, cost, card_type):
        self.name = name
        self.cost = cost
        self.original_cost = cost
        self.type = card_type # 'follower', 'spell', 'amulet'
        self.unique_id: uuid.UUID = uuid.uuid7()
        self.is_generated = False
        # When a card is generated by card effect or other game effects, void id need to be signed to identify it.
        # increase the counter in game state first, then create the UUID
        # sign as a = gamestate.amount_card_generated_from_void[1], player 1.
        # sign as c = gamestate.amount_card_generated_from_void[2], player 2.
        # Otherwise, the card wont be identifiable when repeating action sequences.
        self.void_id: uuid.UUID = uuid.uuid8(0, 0, 0)
        self.description = ""
        self.effect_description = ""
        self.request_card_selection_on_play: str = "" # e.g., "field"
        # field: player field follower
        # field_opponent: opponent field follower
        # field_both: both fields follower
        # field_c: player field any card
        # field_opponent_c: opponent field any card
        # field_both_c: both fields any card
        # if selectable exist, selection cannot be None
        self.request_multi_card_selection_on_play: tuple[str, int] = ("", 0) # e.g., ("field", 2) for selecting up to 2 followers on player field
        # feature to be implemented.
        # the int value must be > 1.
        # usually for effects like "select up to 3 cards from opponent's field, destroy them". Up to 3, but 1 and 2 are also valid selections.
        # but if selectable exist, selection cannot be None, just like request_card_selection_on_play.
        # currently no card use this feature. Update ExampleCard class to test this.
        # note for ui: UISelectionList can have multiselection, but does not support up to n selection feature.
        # As a workaround, compare len(card_selection_list.get_multi_selection) before allowing to proceed.
        # note for ai_player: implement this.
        # note for game logic: implement this.
        self.request_effect_choose_option: list[str] = [] # e.g., ["Option 1", "Option 2"] on playing this card


    def tooltip_str(self):
        s = f"{self.name}\n"
        if self.effect_description:
            s += f"{self.effect_description}\n"
        if self.description:
            s += f"{self.description}\n"
        return s

    def reset_stats(self):
        self.cost = self.original_cost

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None,
                        selected_cards_for_multi_effect: list[Card] | None = None):
        """
        NOTE: No need for drawing field ui as it is handled in game_state.play_card()
        """
        pass

    def on_leave_field_effect(self, mode: str, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox, player: int):
        pass

    def start_of_turn_on_field_effect(self, player: int):
        pass

    def end_of_turn_on_field_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox):
        pass

    def effect_when_player_followers_destroyed(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox, destroyed_follower: Follower):
        """
        triggers when any follower on same side of field is destroyed.
        """
        pass

    def effect_when_opponent_followers_destroyed(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox, destroyed_follower: Follower):
        """
        triggers when any follower on opponent's field is destroyed.
        """
        pass

    def effect_when_either_followers_destroyed(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox, destroyed_follower: Follower):
        """
        triggers when any follower on either side of field is destroyed.
        """
        pass


    def mv(self, org: list[Card], mode: str, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox, player: int):
        """
        move this card from org(like field) to another zone, based on mode.
        available modes: generic, destroy, discard, to_g, banish, to_hand, to_deck_top, to_deck_bottom
        """
        org.remove(self)
        if set_text:
            match mode:
                case "destroy":
                    the_actual_textbox.append_html_text(f"{self}が破壊されたのじゃ。\n")
                case "discard":
                    the_actual_textbox.append_html_text(f"{self}が捨てられたのじゃ。\n")
                case "to_g":
                    the_actual_textbox.append_html_text(f"{self}が墓場に送られたのじゃ。\n")
                case "banish":
                    the_actual_textbox.append_html_text(f"{self}が消滅したのじゃ。\n")
                case "to_hand":
                    the_actual_textbox.append_html_text(f"{self}が手札に戻ったのじゃ。\n")
                case "to_deck_top":
                    the_actual_textbox.append_html_text(f"{self}がデッキの一番上に置かれたのじゃ。\n")
                case "to_deck_bottom":
                    the_actual_textbox.append_html_text(f"{self}がデッキの一番下に置かれたのじゃ。\n")
                case "summon":
                    the_actual_textbox.append_html_text(f"{self}が場に出されたのじゃ。\n")
                case _:
                    the_actual_textbox.append_html_text(f"{self}が移動したのじゃ。\n")

        self.on_leave_field_effect(mode, game_state, draw_ui, set_text, the_actual_textbox, player)
        match mode:
            case "generic" | "destroy" | "discard" | "to_g":
                game_state.graveyard[player].append(self)
            case "banish":
                game_state.banished[player].append(self)
            case "to_hand":
                if len(game_state.hands[player]) < 9:
                    game_state.hands[player].append(self)
                else:
                    game_state.graveyard[player].append(self)
            case "to_deck_top":
                game_state.decks[player].append(self)
            case "to_deck_bottom":
                game_state.decks[player].insert(0, self)
            case "summon":
                if len(game_state.fields[player]) < 5:
                    game_state.fields[player].append(self)
                    if isinstance(self, Follower):
                        self.on_summon_effect()
                else:
                    game_state.graveyard[player].append(self)
            case _:
                raise ValueError("Invalid mode for mv.")
            
        if mode == "destroy" and isinstance(self, Follower):
            for c in game_state.fields[player].copy(): # the player who has his follower just destroyed
                c.effect_when_player_followers_destroyed(game_state, draw_ui, set_text, the_actual_textbox, self)
                c.effect_when_either_followers_destroyed(game_state, draw_ui, set_text, the_actual_textbox, self)
            for c in game_state.fields[3 - player].copy(): # the opponent
                c.effect_when_opponent_followers_destroyed(game_state, draw_ui, set_text, the_actual_textbox, self)
                c.effect_when_either_followers_destroyed(game_state, draw_ui, set_text, the_actual_textbox, self)


    @classmethod
    def cp(cls, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox) -> Card:
        """
        Used to create a generated card with unique void id. A game_state, as long as it is not reset,
        no generated cards can have the same void id.
        """
        try:
            new_card = cls() # should work for all subclasses. i.e.. 飢餓の使徒()
        except Exception as e:
            print(f"Error creating card instance: {e}")
        
        game_state.amount_card_generated_from_void[game_state.current_player] += 1
        new_card.is_generated = True
        a = game_state.amount_card_generated_from_void[1]
        c = game_state.amount_card_generated_from_void[2]
        new_card.void_id = uuid.uuid8(a, 0, c)
        return new_card


class Follower(Card):
    def __init__(self, name, cost, attack, hp, can_enhance):
        super().__init__(name, cost, 'follower')
        self.description_e = ""  # enhanced description
        self.attack = attack
        self.hp = hp
        self.max_hp = hp
        self.original_attack = attack
        self.original_max_hp = hp
        self.can_enhance: bool = can_enhance # use 1 foxtail to enhance
        self.is_enhanced: bool = False
        self.summoned_this_turn: bool = True
        self.enhanced_this_turn: bool = False
        self.request_card_selection_on_enhance: str = ""
        # same as request_card_selection_on_play but for enhance
        # if selectable exist, selection cannot be None
        self.request_multi_card_selection_on_enhance: tuple[str, int] = ("", 0)
        # same as request_multi_card_selection_on_play but for enhance.
        # e.g., ("field_opponent", 2) for selecting up to 2 followers on opponent field when enhancing.
        # the int value must be > 1.
        # if selectable exist, selection cannot be None, just like request_card_selection_on_enhance.
        self.request_effect_choose_option_e: list[str] = []  # effect choice options when enhanced
        self.attack_ability: int = 0  # 0: cannot attack, 1: can attack follower, 2: can attack player
        self.how_many_attacks_max_of_turn: int = 1  # Number of attacks per turn
        self.how_many_attacks_done_of_turn: int = 0  # Number of attacks done this turn
        self.can_attack_this_turn: bool = False
        self.ability_rush: bool = False
        self.ability_super_rush: bool = False
        self.ability_protect: bool = False  # Opponent's followers cannot target leader while this follower is on field
        self.ability_drain: bool = False  # Heals leader when it attacks and deals damage.
        self.ability_lethal: bool = False  # Can destroy any follower it damages, regardless of hp.
    
    def tooltip_str(self):
        s = f"{self.name}\n"
        s += f"攻撃:{self.attack}HP:{self.hp}/{self.max_hp}\n"
        if self.ability_rush:
            s += "【突進】\n"
        if self.ability_super_rush:
            s += "【疾走】\n"
        if self.ability_protect:
            s += "【守護】\n"
        if self.ability_drain:
            s += "【ドレイン】\n"
        if self.ability_lethal:
            s += "【必殺】\n"
        if self.effect_description:
            s += f"{self.effect_description}\n"
        if self.is_enhanced and self.description_e:
            s += f"{self.description_e}\n"
        elif self.description:
            s += f"{self.description}\n"
        return s

    def reset_stats(self):
        self.cost = self.original_cost
        self.attack = self.original_attack
        self.max_hp = self.original_max_hp
        self.hp = self.original_max_hp
        if self.is_enhanced:
            self.is_enhanced = False
            self.can_enhance = True

    def advance_attack_ability(self):
        """
        increase the attack ability by 1, up to 2
        """
        if self.attack_ability < 2:
            self.attack_ability += 1

    def decrease_attack_ability(self):
        """
        decrease the attack ability by 1, down to 0
        """
        if self.attack_ability > 0:
            self.attack_ability -= 1
    
    def on_summon_effect(self):
        # called after on play effect and immediately after assigned to field
        # but before drawing field ui
        if self.ability_rush:
            self.attack_ability = 1
            if self.how_many_attacks_done_of_turn < self.how_many_attacks_max_of_turn:
                self.can_attack_this_turn = True
        if self.ability_super_rush:
            self.attack_ability = 2
            if self.how_many_attacks_done_of_turn < self.how_many_attacks_max_of_turn:
                self.can_attack_this_turn = True
        else:
            self.attack_ability = 0
            self.can_attack_this_turn = False
        self.summoned_this_turn = True
        self.enhanced_this_turn = False
        self.how_many_attacks_done_of_turn = 0

    def start_of_turn_on_field_effect(self, player):
        self.enhanced_this_turn = False
        self.how_many_attacks_done_of_turn = 0
        self.summoned_this_turn = False
        self.advance_attack_ability()
        self.can_attack_this_turn = True

    def after_attack_effect(self):
        self.how_many_attacks_done_of_turn += 1
        if self.how_many_attacks_done_of_turn >= self.how_many_attacks_max_of_turn:
            self.can_attack_this_turn = False

    def on_enhance_effect_default(self):
        if self.can_enhance and not self.enhanced_this_turn:
            self.attack += 2
            self.hp += 2
            self.max_hp += 2
            self.can_enhance = False
            self.enhanced_this_turn = True
            self.is_enhanced = True
            self.advance_attack_ability()
            if self.how_many_attacks_done_of_turn < self.how_many_attacks_max_of_turn:
                self.can_attack_this_turn = True
            
    def on_enhance_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                          selected_card_for_effect: Card | None, effect_choice: str | None = None,
                          selected_cards_for_multi_effect: list[Card] | None = None):
        self.on_enhance_effect_default()

    def take_damage(self, damage_amount: int, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                    attacker: Card | None, is_battle_damage: bool = False):
        """
        Take card effect damage unless is_battle_damage is True.
        When hp <= 0, it is destroyed.
        """
        self.hp -= damage_amount
        # find out which player's field this follower is on
        for p in [1, 2]:
            if self in game_state.fields[p]:
                player = p
                break
        assert player in [1, 2], "Follower not found on any player's field."
        if set_text:
            the_actual_textbox.append_html_text(f"プレイヤー{player}の{self}が{attacker}から{damage_amount}ダメージを受けたのじゃ。\n")
        if self.hp <= 0 or (isinstance(attacker, Follower) and attacker.ability_lethal and is_battle_damage):
            self.mv(game_state.fields[player], mode="destroy", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=player)
        else:
            self.effect_after_taking_damage(damage_amount, game_state, draw_ui, set_text, the_actual_textbox)
        if draw_ui:
            game_state.draw_field_ui(player)


    def effect_after_taking_damage(self, damage_amount: int, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox):
        """
        Trigger effect after follower taking damage, unless it is destroyed by damage.
        """
        pass


    def stats_change_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                             imposter: Card | None, attack_change: int, hp_change: int):
        """
        Handle generic stat changes effect like -1/-1, +2/+0, etc.
        Unlike take damage, max_hp is also affected by negative or positive hp changes.
        When hp <= 0, it is banished.
        """
        self.attack += attack_change
        self.hp += hp_change
        self.max_hp += hp_change
        for p in [1, 2]:
            if self in game_state.fields[p]:
                player = p
                break
        assert player in [1, 2], "Follower not found on any player's field."
        # make no sense for atk to be less than 0
        if self.attack < 0:
            self.attack = 0
        # clean up if hp goes below 0
        if self.hp <= 0:
            self.mv(game_state.fields[player], mode="banish", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=player)
        else:
            if set_text:
                the_actual_textbox.append_html_text(f"プレイヤー{player}の{self}のステータスが{imposter}によって変更されたのじゃ：")
                # +n/-nを正しく表示するのじゃ
                attack_str = f"+{attack_change}" if attack_change >= 0 else f"-{attack_change}"
                hp_str = f"+{hp_change}" if hp_change >= 0 else f"-{hp_change}"
                the_actual_textbox.append_html_text(f"{attack_str}/{hp_str}なのじゃ。\n")


    def stats_change_effect_simple(self, attack_change: int, hp_change: int, draw_ui, set_text, the_actual_textbox):
        """
        A simplified version of stats_change_effect. No need for game state.
        """
        assert hp_change >= 0, "Not supported in simple version."
        self.attack += attack_change
        self.hp += hp_change
        self.max_hp += hp_change
        # clean up if hp goes below 0
        if self.hp <= 0:
            pass
        if self.attack < 0:
            self.attack = 0
        if set_text:
            the_actual_textbox.append_html_text(f"{self}のステータスが変更されたのじゃ：")
            # +n/-nを正しく表示するのじゃ
            attack_str = f"+{attack_change}" if attack_change >= 0 else f"-{attack_change}"
            hp_str = f"+{hp_change}" if hp_change >= 0 else f"-{hp_change}"
            the_actual_textbox.append_html_text(f"{attack_str}/{hp_str}なのじゃ。\n")



    def __repr__(self):
        return f"{self.name}({self.attack}/{self.hp})"


class Spell(Card):
    def __init__(self, name, cost):
        super().__init__(name, cost, 'spell')
    
    def __repr__(self):
        return f"{self.name}"


class Amulet(Card):
    def __init__(self, name, cost):
        super().__init__(name, cost, 'amulet')
        self.counter_name: str = ""  # name of the counter, e.g., "soul"
        self.counter: int = 0  # for amulets that have counters
        self.counter_max: int = 0  # maximum counter value for the amulet
        self.amulet_value_for_evaluate: int = self.cost * 4  # value used in AI evaluation of game state when on field
    
    def decrease_counter(self, amount: int =1):
        """
        Return True if counter reaches 0, else False.
        """
        self.counter = max(0, self.counter - amount)
        if self.counter == 0:
            # amulet is destroyed when counter reaches 0
            # not handled here
            return True
        return False

    def destroy_amulet(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox, player: int):
        """
        Destroy this amulet on the field of the specified player.
        Usually called when counter reaches 0.
        """
        self.mv(game_state.fields[player], mode="destroy", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=player)

    def tooltip_str(self):
        s = f"{self.name}\n"
        if self.counter_name:
            s += f"{self.counter_name}: {self.counter}\n"
        if self.effect_description:
            s += f"{self.effect_description}\n"
        if self.description:
            s += f"{self.description}\n"
        return s

    def __repr__(self):
        return f"{self.name}"


# ==============================
# Followers
# Each cost is evaluated as 4 points
# ==============================

class ゴブリン(Follower):
    """
    target value: 1 * 4 = 4 points
    2/2 stats: 4 points
    """
    def __init__(self):
        super().__init__(name="ゴブリン", cost=1, attack=2, hp=2, can_enhance=True)
        self.description = "ゴブリンの世界にあるのはエモノだけ。欲しいものを持った獲物、奪い取って身に着けた得物。"
        self.description_e = "ゴブリンは純粋に、無垢に、エモノを追いかけ回す。彼らを見れば分かる通り、純粋も無垢も善の同義語ではない。"


class ファイター(Follower):
    """
    target value: 2 * 4 = 8 points
    4/4 stats: 8 points
    """
    def __init__(self):
        super().__init__(name="ファイター", cost=2, attack=4, hp=4, can_enhance=False)
        self.description = "争いだらけの世界の中で、頼れるのは自分だけ。この得た力だけは、決して裏切らない。"


class ゴリアテ(Follower):
    """
    target value: 3 * 4 = 12 points
    6/6 stats: 12 points
    """
    def __init__(self):
        super().__init__(name="ゴリアテ", cost=3, attack=6, hp=6, can_enhance=True)
        self.description = "見上げた時にはもう遅い。巨人はお前を見下ろすこともなく踏み潰す。"
        self.description_e = "思い出が染みついた家も、思い出を振り返る人も、巨人にとっては踏みしめるべき道に過ぎない。"


class ガブリエル(Follower):
    """
    target value: 4 * 4 = 16 points
    4/3 stats: 7 points, buff effect: 7 points
    total value: 14 points
    """
    def __init__(self):
        super().__init__(name="ガブリエル", cost=4, attack=4, hp=3, can_enhance=False)
        self.effect_description = "場に出す時、他のフォロワー1体を選ぶ。それは攻撃力+4/体力+3する。"
        self.request_card_selection_on_play = "field"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Follower | None, effect_choice: str | None):
        if selected_card_for_effect is not None:
            selected_card_for_effect.stats_change_effect(game_state, draw_ui, set_text, the_actual_textbox,
                                                         imposter=self, attack_change=4, hp_change=3)


class ハンサ(Follower):
    """
    target value: 1 * 4 = 4 points
    base 0/2 stats: 2 points, effect average +2 attack: 2 points
    total value: 4 points
    """
    def __init__(self):
        super().__init__(name="ハンサ", cost=1, attack=0, hp=2, can_enhance=False)
        self.description = "聖鳥は純朴な瞳を誘い、旺盛な食欲を誘う。「ボクはキミたちの心を映す鏡さ！」"
        self.effect_description = "場に出す時、これは攻撃力+Xする。Xは「自分のデッキの上1枚カードのコスト」である。"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        if game_state.decks[game_state.current_player]:
            top_card = game_state.decks[game_state.current_player][-1]
            self.stats_change_effect_simple(attack_change=top_card.cost, hp_change=0, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox)


class 唯我の絶傑マゼルベイン(Follower):
    """
    target value: 4 * 4 = 16 points
    5/5 stats: 10 points, end of turn effect: countless take downs since release, usually far above 6 points
    total value: at least 20 points
    """
    def __init__(self):
        super().__init__(name="唯我の絶傑・マゼルベイン", cost=4, attack=5, hp=5, can_enhance=True)
        self.effect_description = "自分のエンドフェイズが来た、自分のフェルトこれしかないとき、相手の場のフォロワーすべてに3ダメージ。進化後なら5ダメージ。"

    def end_of_turn_on_field_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox):
        if len(game_state.fields[game_state.current_player]) == 1 and self == game_state.fields[game_state.current_player][0]: # only this card on field
            damage_amount = 5 if self.is_enhanced else 3
            for c in game_state.fields[game_state.opponent].copy():
                if isinstance(c, Follower):
                    c.take_damage(damage_amount, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)


class 機構翼の少女ローザ(Follower):
    """
    target 2 * 4 = 8 points
    value: 1 + 3 + 3(protect) + 4(draw card) = 11 points
    """
    def __init__(self):
        super().__init__(name="機構翼の少女・ローザ", cost=2, attack=1, hp=3, can_enhance=True)
        self.description = "相応なんでしょう、私には、この鳥籠の世界が。飛べるだけで幸せなんです。だから、きっとこれでいい。"
        self.description_e = "壮観なんでしょう、本当の空から見下ろす景色は。桃源郷はここなんです。だけど、いつかはきっと――。"
        self.effect_description = "進化時1枚引く。"
        self.ability_protect = True

    def on_enhance_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                          selected_card_for_effect: Card | None, effect_choice: str | None = None,
                          selected_cards_for_multi_effect: list[Card] | None = None):
        self.on_enhance_effect_default()
        game_state.draw_card_by_effect(game_state.current_player, 1, draw_ui, set_text)


class 飢餓の使徒(Follower):
    """
    target value: 2 * 4 = 8 points
    value: 2 + 2 + 1(rush) + at least 3 = 8 points
    """
    def __init__(self):
        super().__init__(name="飢餓の使徒", cost=2, attack=2, hp=2, can_enhance=True)
        self.description_e = "必死になって、追い立てられて、身を捩るほどに苦悩して。無垢なままでは終わってしまうわよ。"
        self.effect_description = "場に出す時、自分の場の他のフォロワー1体を選ぶ。それは突進を持つ。" \
        "進化時、場のフォロワー1体を選ぶ。それに3ダメージ。それは攻撃力+3する。これを選ぶ時、この効果は無効になる。"
        self.request_card_selection_on_enhance = "field_both"
        self.request_card_selection_on_play = "field"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Follower | None, effect_choice: str | None):
        if selected_card_for_effect is not None:
            if selected_card_for_effect.attack_ability < 1:
                selected_card_for_effect.advance_attack_ability()
                if selected_card_for_effect.how_many_attacks_done_of_turn < selected_card_for_effect.how_many_attacks_max_of_turn:
                    selected_card_for_effect.can_attack_this_turn = True
            selected_card_for_effect.ability_rush = True

    def on_enhance_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                          selected_card_for_effect: Card | None, effect_choice: str | None = None,
                          selected_cards_for_multi_effect: list[Card] | None = None):
        self.on_enhance_effect_default()
        target = selected_card_for_effect
        if target is not None and isinstance(target, Follower) and target != self:
            target.take_damage(3, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
            if target.hp > 0:
                target.stats_change_effect(game_state, draw_ui, set_text, the_actual_textbox,
                                       imposter=self, attack_change=3, hp_change=0)


class 飢餓の絶傑ギルネリーゼ(Follower):
    """
    target value: 3 * 4 = 12 points
    value: drain ability: 2 points, versatile +4/-4 effect: at least 4 points, generates card effect: 4 points
    attack hp 2/2: 4 points
    total value: 14+ points
    """
    def __init__(self):
        super().__init__(name="飢餓の絶傑・ギルネリーゼ", cost=3, attack=2, hp=2, can_enhance=False)
        self.effect_description = "場に出す時、場の他のフォロワー1体を選ぶ。それに4ダメージ。それは攻撃力+4する。" \
        "自分のフォロワーの場合、『飢餓の使徒』1枚；相手のフォロワーの場合、『飢餓の輝き』1枚を手札に加える。"
        self.request_card_selection_on_play = "field_both"
        self.ability_drain = True

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        target = selected_card_for_effect
        if target is not None and isinstance(target, Follower) and target != self:

            if target in game_state.fields[game_state.current_player]:
                new_card = 飢餓の使徒.cp(game_state, draw_ui, set_text, the_actual_textbox)
            elif target in game_state.fields[game_state.opponent]:
                new_card = 飢餓の輝き.cp(game_state, draw_ui, set_text, the_actual_textbox)
            else:
                raise ValueError("Target follower not found on either player's field.")
            
            target.take_damage(4, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
            if target.hp > 0:
                target.stats_change_effect(game_state, draw_ui, set_text, the_actual_textbox,
                                       imposter=self, attack_change=4, hp_change=0)
            # add card to hand
            new_card.mv([new_card], mode="to_hand", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=game_state.current_player)


class 不殺の絶傑エズディア(Follower):
    """
    target value: 4 * 4 = 16 points
    value: 6/6 stats: 12 points, field effect: conditional 6 damage: 6 points
    slightly difficult to utilize
    total value: 18 points
    """
    def __init__(self):
        super().__init__(name="不殺の絶傑・エズディア", cost=4, attack=6, hp=6, can_enhance=True)
        self.effect_description = "場に出す時、すべてのフォロワーとリーダーの中で、体力が最も低いものにすべて6ダメージ。" \
        "進化する時同じ効果を持つ。これ若しくは自分のリーダーが最も低い場合、自分のリーダーだけに6ダメージを与える。"


    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                    selected_card_for_effect: Card | None, effect_choice: str | None):
        # Compute minimum HP across followers and leaders
        min_hp_f1 = min((f.hp for f in game_state.fields[1] if isinstance(f, Follower)), default=None)
        min_hp_f2 = min((f.hp for f in game_state.fields[2] if isinstance(f, Follower)), default=None)
        min_candidates = [game_state.hp[1], game_state.hp[2]]
        if min_hp_f1 is not None:
            min_candidates.append(min_hp_f1)
        if min_hp_f2 is not None:
            min_candidates.append(min_hp_f2)
        overall_min_hp = min(min_candidates)

        # Collect followers at the minimum HP (deterministic order)
        followers_min = [
            f for f in (*game_state.fields[1], *game_state.fields[2])
            if isinstance(f, Follower) and f.hp == overall_min_hp
        ]

        # If self is among the lowest or our leader is the lowest, restrict to own leader only
        own_leader_is_lowest = (
            (game_state.current_player == 1 and game_state.hp[1] == overall_min_hp) or
            (game_state.current_player == 2 and game_state.hp[2] == overall_min_hp)
        )
        restrict_to_own_leader = (self in followers_min) or own_leader_is_lowest

        # Decide leader targets
        if restrict_to_own_leader:
            leader_targets = [game_state.current_player]
            followers_min = []  # Effect text says to hit only own leader in these cases
        else:
            leader_targets = [p for p in (1, 2) if game_state.hp[p] == overall_min_hp]

        if set_text:
            the_actual_textbox.append_html_text("最も体力の低い者へ、等しく裁きを下すのじゃ…！\n")

        # Apply damage
        for f in followers_min:
            f.take_damage(6, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
        for p in leader_targets:
            game_state.player_take_damage(p, 6, draw_ui, set_text)


    def on_enhance_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                          selected_card_for_effect: Card | None, effect_choice: str | None = None,
                          selected_cards_for_multi_effect: list[Card] | None = None):
        self.on_enhance_effect_default()
        # same effect as on play
        self.on_play_effect(game_state, draw_ui, set_text, the_actual_textbox, selected_card_for_effect, effect_choice=None)


class 真実の絶傑ライオ(Follower):
    """
    target value: 4 * 4 = 16 points
    value: 7/7 stats: 14 points, average discard 2 cards -8, destroy 2, 10 points
    Very difficult to use
    total value: 16- points
    """
    def __init__(self):
        super().__init__(name="真実の絶傑・ライオ", cost=4, attack=7, hp=7, can_enhance=True)
        self.effect_description = "場に出す時、手札のスペルカードをすべて捨てる。相手の場のフォロワーを左から順番にX枚を9ダメージ。" \
        "Xは捨てたスペルカードの枚数である。手札にスペルカードがない若しくはターゲットがない時、自分のリーダーに9ダメージ。"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        player = game_state.current_player
        spell_cards_to_discard = [c for c in game_state.hands[player] if isinstance(c, Spell)]
        # Discard all spell cards from hand to graveyard
        bullet = len(spell_cards_to_discard)
        for c in spell_cards_to_discard:
            c.mv(game_state.hands[player], "discard", game_state, draw_ui, set_text, the_actual_textbox, player=player)
        if bullet > 0:
            # Deal 9 damage to opponent's followers from left to right
            if game_state.fields[game_state.opponent]:
                for c in game_state.fields[game_state.opponent].copy():
                    if bullet <= 0:
                        break
                    if isinstance(c, Follower):
                        c.take_damage(9, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
                        bullet -= 1
        else:
            # No spell cards to discard, deal 9 damage to own leader
            game_state.player_take_damage(player, 9, draw_ui, set_text)
        # if there are bullets remain, these will damage own leader
        if bullet > 0:
            while bullet > 0:
                game_state.player_take_damage(player, 9, draw_ui, set_text)
                bullet -= 1
                if game_state.concluded:
                    break


class 侮蔑の絶傑ガルミーユ(Follower):
    """
    target value: 4 * 4 = 16 points
    value: 5/7 stats: 12 points, effect damage to leader: average 4 points
    total value: 16 points
    """
    def __init__(self):
        super().__init__(name="侮蔑の絶傑・ガルミーユ", cost=4, attack=5, hp=7, can_enhance=True)
        self.effect_description = "自分のターン中、これがダメージを受けたとき、相手のリーダーに2ダメージ。" \
        "進化後なら、4ダメージ。"
    
    def effect_after_taking_damage(self, damage_amount: int, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox):
        for p in [1, 2]:
            if self in game_state.fields[p]:
                player = p
                break
        assert player in [1, 2], "Follower not found on any player's field."
        if player == game_state.current_player:
            damage_to_opponent = 4 if self.is_enhanced else 2
            if set_text:
                the_actual_textbox.append_html_text(f"侮蔑の絶傑・ガルミーユの効果で、プレイヤー{game_state.opponent}に{damage_to_opponent}ダメージを与えるのじゃ。\n")
            game_state.player_take_damage(game_state.opponent, damage_to_opponent, draw_ui, set_text)


class 神弓の座天使リリエル(Follower):
    """
    target value: 2 * 4 = 8 points
    value: 2/5 stats: 7 points, effect prevent ability damage: conditional usage
    """
    def __init__(self):
        super().__init__(name="神弓の座天使・リリエル", cost=2, attack=2, hp=5, can_enhance=False)
        self.effect_description = "これがいる限り、自分のリーダーは能力によるダメージを受けない。"


class 簒奪の絶傑オクトリス(Follower):
    """
    target value: 3 * 4 = 12 points
    value: 2/2 stats: 4 points, effect steal card: 4 + 4 points
    total value: 12 points
    """
    def __init__(self):
        super().__init__(name="簒奪の絶傑・オクトリス", cost=3, attack=2, hp=2, can_enhance=True)
        self.effect_description = "進化する時、相手の手札のカードを1枚選び、それを自分の手札に加える。"
        self.request_card_selection_on_enhance = "hand_opponent"

    def on_enhance_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                            selected_card_for_effect: Card | None, effect_choice: str | None = None,
                            selected_cards_for_multi_effect: list[Card] | None = None):
        self.on_enhance_effect_default()
        target = selected_card_for_effect
        if target is not None and target in game_state.hands[game_state.opponent]:
            target.mv(game_state.hands[game_state.opponent], "to_hand", game_state, draw_ui, set_text, the_actual_textbox, player=game_state.current_player)
            if set_text:
                the_actual_textbox.append_html_text(f"簒奪の絶傑・オクトリスの効果で、プレイヤー{game_state.current_player}はプレイヤー{game_state.opponent}の手札から{target}を奪ったのじゃ。\n")


class オウルキャット(Follower):
    """
    target value: 1 * 4 = 4 points
    value: 4 points
    """
    def __init__(self):
        super().__init__(name="オウルキャット", cost=1, attack=2, hp=2, can_enhance=True)
        self.effect_description = "進化する時、攻撃力或いはHP1以下のフォロワーを全部消滅させる。" \
        "消滅の効果を発動するとき、自分の手札を全部消滅させる。"
        self.description = "飽食の獣、尚も飢え、昼の路地裏に想いを馳せる。執拗な獣、尚も飢え、夜の隙間に望みを託した。"
        self.description_e = "褒賞はすぐそこに。獲物、今まさにフクロの鼠。忍び寄る体躯、かっぴらく双眼。これまさにネコに鰹節。"

    def on_enhance_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                            selected_card_for_effect: Card | None, effect_choice: str | None = None,
                            selected_cards_for_multi_effect: list[Card] | None = None):
            self.on_enhance_effect_default()
            player = game_state.current_player
            # banish all followers with attack or hp 1 or less
            activated_effect = False
            for p in [1, 2]:
                for c in game_state.fields[p].copy():
                    if isinstance(c, Follower) and (c.attack <= 1 or c.hp <= 1):
                        c.mv(game_state.fields[p], mode="banish", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=p)
                        activated_effect = True
                if draw_ui:
                    game_state.draw_field_ui(p)
            if game_state.hands[player] and activated_effect:
                # banish all cards in hand
                for c in game_state.hands[player].copy():
                    c.mv(game_state.hands[player], mode="banish", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=player)
                assert len(game_state.hands[player]) == 0, "All cards in hand should have been banished."
                if draw_ui:
                    game_state.draw_hand_ui(player)


class 円卓の騎士ガウェイン(Follower):
    """
    value: average 2 followers in hand. So its cost 3 6/5 = 12 11 points
    """
    def __init__(self):
        super().__init__(name="円卓の騎士・ガウェイン", cost=5, attack=6, hp=5, can_enhance=False)
        self.effect_description = "場に出す時、狐尾をX回復する。Xは自分の手札のフォロワーの数である。"

    def on_play_effect(self, game_state, draw_ui, set_text, the_actual_textbox, selected_card_for_effect, effect_choice):
        player = game_state.current_player
        num_followers_in_hand = sum(1 for c in game_state.hands[player] if isinstance(c, Follower))
        # NOTE: adding foxtail manually here. Not good.
        game_state.foxtail[player] += num_followers_in_hand
        if set_text:
            the_actual_textbox.append_html_text(f"円卓の騎士・ガウェインの効果で、プレイヤー{player}は狐尾を{num_followers_in_hand}回復したのじゃ。\n")
        if draw_ui:
            game_state.draw_tail_ui(player)


class スターフェニックス(Follower):
    """
    """
    def __init__(self):
        super().__init__(name="スターフェニックス", cost=4, attack=2, hp=2, can_enhance=True)
        self.effect_description = "スペルカードをプレイする時、これを墓場から場に出し、すべての状態をリセットされる。"


class 白翼の守護神アイテール(Follower):
    """
    """
    def __init__(self):
        super().__init__(name="白翼の守護神・アイテール", cost=7, attack=4, hp=7, can_enhance=False)
        self.ability_protect = True
        self.effect_description = "場に出す時、手札からコストX以下のフォロワー1体を選び、場に出す。それは場に出す効果を発動しない。Xは自分の手札のフォロワーの数である。"
        self.request_card_selection_on_play = "hand_follower_aiteru"

    def on_play_effect(self, game_state, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect, effect_choice):
        target = selected_card_for_effect
        player = game_state.current_player
        if target is not None and target in game_state.hands[player]:
            target.mv(game_state.hands[player], "summon", game_state, draw_ui, set_text, the_actual_textbox, player=player)


class キラキラヒーラー(Follower):
    """
    """
    def __init__(self):
        super().__init__(name="キラキラヒーラー", cost=2, attack=2, hp=2, can_enhance=True)
        self.effect_description = "自分の手札にスペルカードがあるなら、リーダーに2回復。進化後同じ効果。"
        self.description = "「ほっとけないよ、そんなケガ！だってやばくて、やばいもん！しっかり治すよ、そんなケガ！ふわふわヒールの出番だよ！」"
        self.description_e = "「ほったらかしにしちゃったら、どんなケガでもダイサンジ！しなくていいガマンはしない！痛くなったら頼ってね！」"

    def on_play_effect(self, game_state, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect, effect_choice):
        player = game_state.current_player
        has_spell_in_hand = any(isinstance(c, Spell) for c in game_state.hands[player])
        if has_spell_in_hand:
            game_state.player_heal(player, 2, draw_ui, set_text)
        else:
            if set_text:
                the_actual_textbox.append_html_text(f"キラキラヒーラーの効果は発動しなかったのじゃ。\n")

    def on_enhance_effect(self, game_state, draw_ui, set_text, the_actual_textbox,
                            selected_card_for_effect, effect_choice=None,
                            selected_cards_for_multi_effect=None):
        self.on_enhance_effect_default()
        self.on_play_effect(game_state, draw_ui, set_text, the_actual_textbox,
                            selected_card_for_effect, effect_choice=None)


class ミスティアストロジスト(Follower):
    """
    """
    def __init__(self):
        super().__init__(name="ミスティアストロジスト", cost=3, attack=1, hp=1, can_enhance=False)
        self.description = "ほんの小さな瞬きからさえ、彼女は目を離しはしない。素人には分からない、輝きの価値を知るからだ。"
        self.effect_description = "X枚引く。Xは自分の手札のフォロワーの数である。"

    def on_play_effect(self, game_state, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect, effect_choice):
        player = game_state.current_player
        num_followers_in_hand = sum(1 for c in game_state.hands[player] if isinstance(c, Follower))
        game_state.draw_card_by_effect(player, num_followers_in_hand, draw_ui, set_text)


class 水竜神の巫女(Follower):
    """
    """
    def __init__(self):
        super().__init__(name="水竜神の巫女", cost=3, attack=6, hp=5, can_enhance=False)
        self.effect_description = "デッキの上からX枚捨てる。Xは自分の手札のフォロワーの数である。" \
        "これは+0/+Xする。"

    def on_play_effect(self, game_state, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect, effect_choice):
        player = game_state.current_player
        num_followers_in_hand = sum(1 for c in game_state.hands[player] if isinstance(c, Follower))
        # Discard X cards from top of deck to graveyard
        actual_discarded = 0
        for _ in range(num_followers_in_hand):
            if game_state.decks[player]:
                top_card = game_state.decks[player][-1]
                top_card.mv(game_state.decks[player], mode="discard", game_state=game_state, 
                            draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=player)
                actual_discarded += 1

        # Increase HP by actual discarded amount
        self.stats_change_effect_simple(0, actual_discarded, draw_ui, set_text, the_actual_textbox)


class 黄金都市の姫リテュエル(Follower):
    """
    """
    def __init__(self):
        super().__init__(name="黄金都市の姫・リテュエル", cost=2, attack=2, hp=2, can_enhance=True)
        self.description_e = "宝殿の最奥には、黄金と化した姫が眠っている。資格持つ者訪れし日に、姫は再び目覚めるだろう。"
        self.effect_description = "場に出す時、自分のリーダーに2ダメージ。進化時、相手のフォロワー1体を選ぶ、それを消滅させる。"
        self.request_card_selection_on_enhance = "field_opponent"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        player = game_state.current_player
        game_state.player_take_damage(player, 2, draw_ui, set_text)
        if set_text:
            the_actual_textbox.append_html_text(f"黄金都市の姫・リテュエルの効果で、プレイヤー{player}は2ダメージを受けたのじゃ。\n")

    def on_enhance_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                          selected_card_for_effect: Card | None, effect_choice: str | None = None,
                          selected_cards_for_multi_effect: list[Card] | None = None):
        self.on_enhance_effect_default()
        target = selected_card_for_effect
        if target is not None and target in game_state.fields[game_state.opponent]:
            target.mv(game_state.fields[game_state.opponent], mode="banish", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=game_state.opponent)
            if set_text:
                the_actual_textbox.append_html_text(f"黄金都市の姫・リテュエルの効果で、プレイヤー{game_state.opponent}の{target}が消滅したのじゃ。\n")


class 癒しの奏者アンリエット(Follower):
    """
    """
    def __init__(self):
        super().__init__(name="癒しの奏者・アンリエット", cost=3, attack=2, hp=4, can_enhance=False)
        self.description = "「砲声轟く戦地にあっても、私の音色は響き渡るわ。調べに込めるは癒しの祈り。あぁ、平穏があらんことを」"
        self.effect_description = "場に出す時、自分の場のフォロワー1体を選ぶ。それは+2/+2し、突進を持つ。"
        self.request_card_selection_on_play = "field"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Follower | None, effect_choice: str | None):
        target = selected_card_for_effect
        if target is not None and target in game_state.fields[game_state.current_player]:
            target.stats_change_effect(game_state, draw_ui, set_text, the_actual_textbox,
                                       imposter=self, attack_change=2, hp_change=2)
            if target.attack_ability < 1:
                target.advance_attack_ability()
                if target.how_many_attacks_done_of_turn < selected_card_for_effect.how_many_attacks_max_of_turn:
                    target.can_attack_this_turn = True
            target.ability_rush = True
            if set_text:
                the_actual_textbox.append_html_text(f"癒しの奏者・アンリエットの効果で、プレイヤー{game_state.current_player}の{target}は+2/+2し、突進を得たのじゃ。\n")


class フレイルナイト(Follower):
    """
    """
    def __init__(self):
        super().__init__(name="フレイルナイト", cost=3, attack=2, hp=2, can_enhance=False)
        self.description = "「骨まで砕く、我が一撃！お前の頭上に飛来する！熾烈な戦場、恐れはしない！この剛技にて時代を変える！」"
        self.effect_description = "場のフォロワー1体を選ぶ。それとそれのリーダーにXダメージ。Xは自分の手札のフォロワーの数である。"
        self.request_card_selection_on_play = "field_both"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Follower | None, effect_choice: str | None):
        target = selected_card_for_effect
        # find out the player who owns the target
        for p in [1, 2]:
            if target in game_state.fields[p]:
                target_owner = p
                break
        player = game_state.current_player
        num_followers_in_hand = sum(1 for c in game_state.hands[player] if isinstance(c, Follower))
        if target is not None and num_followers_in_hand > 0:
            target.take_damage(num_followers_in_hand, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
            # Deal damage to leader
            game_state.player_take_damage(target_owner, num_followers_in_hand, draw_ui, set_text)


class お爺さんとお婆さん(Follower):
    """
    """
    def __init__(self):
        super().__init__(name="お爺さんとお婆さん", cost=3, attack=1, hp=1, can_enhance=False)
        self.description = "おじいさんは山へ鬼狩りに、おばあさんは川へ鬼の皮を洗いに。「これが異国の悪魔退治？絵本で見るよりずっと刺激的ね！」"
        self.effect_description = "自分のエンドフェイズが来た時、これを手札に戻す。"
        self.ability_lethal = True
        self.ability_rush = True

    def end_of_turn_on_field_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox):
        for p in [1, 2]:
            if self in game_state.fields[p]:
                self_owner = p
                break

        if self in game_state.fields[self_owner]:
            self.mv(game_state.fields[self_owner], mode="to_hand", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=self_owner)


class ExampleCard(Follower):
    """
    Used to test new features.
    Currently testing: request_multi_card_selection_on_enhance
    """
    def __init__(self):
        super().__init__(name="Example Card", cost=1, attack=1, hp=1, can_enhance=True)
        self.effect_description = "進化する時、相手の場のフォロワーを1体選ぶ、それに1ダメージ。" \
                                  "さらに、相手の場のフォロワーを2体まで選ぶ。それらを破壊する。"
        self.request_card_selection_on_enhance = "field_opponent"
        self.request_multi_card_selection_on_enhance = ("field_opponent", 2)

    def on_enhance_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                          selected_card_for_effect: Card | None, effect_choice: str | None = None,
                          selected_cards_for_multi_effect: list[Card] | None = None):
        self.on_enhance_effect_default()
        # Effect 1: Deal 1 damage to single selected card
        if selected_card_for_effect:
            if isinstance(selected_card_for_effect, Follower) and selected_card_for_effect in game_state.fields[game_state.opponent]:
                selected_card_for_effect.take_damage(1, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
        # Effect 2: Destroy up to 2 selected cards
        if selected_cards_for_multi_effect:
            for target in selected_cards_for_multi_effect:
                if isinstance(target, Follower) and target in game_state.fields[game_state.opponent]:
                    target.mv(game_state.fields[game_state.opponent], mode="destroy",
                              game_state=game_state, draw_ui=draw_ui, set_text=set_text,
                              the_actual_textbox=the_actual_textbox, player=game_state.opponent)



# ==============================
# Spells
# ==============================

class 天なる大河(Spell):
    """
    target value: 1 * 4 = 4 points
    actual value cannot be easily determined
    """
    def __init__(self):
        super().__init__(name="天なる大河", cost=1)
        self.description = "宝石を零したような光景を、憧憬するは人の常。神話となった者だけが、憧れ叶えて天へと至る。"
        self.effect_description = "手札の全てのカードをデッキの下に置く。同じ枚数+1枚のカードをデッキから引く。"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        player = game_state.current_player
        num_cards = len(game_state.hands[player])
        for c in game_state.hands[player].copy():
            c.mv(game_state.hands[player], mode="to_deck_bottom", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=player)
        game_state.draw_card_by_effect(player, num_cards + 1, draw_ui, set_text)


class 神秘の指輪(Spell):
    """
    """
    def __init__(self):
        super().__init__(name="神秘の指輪", cost=1)
        self.description = "本懐を果たし、勇者は運命の死を迎えた。神秘の伝承は指輪に宿り、次なる勇者を待ち望む。"
        self.effect_description = "自分の手札1枚を選ぶ、それをデッキの下に置く。2枚引く。"
        self.request_card_selection_on_play = "hand"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        player = game_state.current_player
        if selected_card_for_effect is not None and selected_card_for_effect in game_state.hands[player]:
            selected_card_for_effect.mv(game_state.hands[player], mode="to_deck_bottom", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=player)
            if set_text:
                the_actual_textbox.append_html_text(f"神秘の指輪の効果で、プレイヤー{player}は手札の{selected_card_for_effect}をデッキの下に置いたのじゃ。\n")
            # Draw 2 cards
            game_state.draw_card_by_effect(player, 2, draw_ui, set_text)
        else:
            if set_text:
                the_actual_textbox.append_html_text(f"神秘の指輪の効果は発動しなかったのじゃ。\n")


class ミヒライテ(Spell):
    """
    target value: 1 * 4 = 4 points
    actual value usually 3 points
    """
    def __init__(self):
        super().__init__(name="ミヒライテ", cost=1)
        self.effect_description = "自分の場のフォロワー1体を選ぶ。それは攻撃力+2/体力+1する。それが『唯我の絶傑・マゼルベイン』なら、代わりに攻撃力+4/体力+2する。" \
        "自分の場のフォロワーがないとき、相手のリーダーに1ダメージ。"
        self.request_card_selection_on_play = "field"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Follower | None, effect_choice: str | None):
        if selected_card_for_effect is not None:
            if selected_card_for_effect.name == "唯我の絶傑・マゼルベイン":
                selected_card_for_effect.stats_change_effect(game_state, draw_ui, set_text, the_actual_textbox,
                                                             imposter=self, attack_change=4, hp_change=2)
            else:
                selected_card_for_effect.stats_change_effect(game_state, draw_ui, set_text, the_actual_textbox,
                                                             imposter=self, attack_change=2, hp_change=1)
        else:
            game_state.player_take_damage(game_state.opponent, 1, draw_ui, set_text)


class フェアリーアサルト(Spell):
    """
    target value: 2 * 4 = 8 points
    actual value usually 6 points but leader damage very strong
    """
    def __init__(self):
        super().__init__(name="フェアリーアサルト", cost=2)
        self.effect_description = "場のフォロワー1体を選び、それに6ダメージ。" \
        "場にフォロワーがないとき、相手のリーダーに6ダメージ。"
        self.request_card_selection_on_play = "field_both"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        if selected_card_for_effect is not None and isinstance(selected_card_for_effect, Follower):
            selected_card_for_effect.take_damage(6, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
        else:
            game_state.player_take_damage(game_state.opponent, 6, draw_ui, set_text)


class 飢餓の輝き(Spell):
    """
    target value: 2 * 4 = 8 points
    actual value 6+ points
    """
    def __init__(self):
        super().__init__(name="飢餓の輝き", cost=2)
        self.effect_description = "場のフォロワー1体を選ぶ。それに4ダメージ。それは攻撃力+2する。"
        self.request_card_selection_on_play = "field_both"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        if selected_card_for_effect is not None and isinstance(selected_card_for_effect, Follower):
            selected_card_for_effect.take_damage(4, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
            if selected_card_for_effect.hp > 0:
                selected_card_for_effect.stats_change_effect(game_state, draw_ui, set_text, the_actual_textbox,
                                                             imposter=self, attack_change=2, hp_change=0)
        else:
            if set_text:
                the_actual_textbox.append_html_text("飢餓の輝きの効果は発動しなかったのじゃ。\n")


class 真実の宣告(Spell):
    """
    target value: 8
    value: technical copy 8 points (equal to exactly 2 draw), return to deck only useful in specific situations 0 points
    total value: 8 points
    """
    def __init__(self):
        super().__init__(name="真実の宣告", cost=2)
        self.effect_description = "手札の他のスペルカードを一つ選び、下記から1つの効果を選択し発動する。【1】それをデッキの下に置く。" \
        "【2】それを1枚複写し、手札に加える。"
        self.request_card_selection_on_play = "hand_spell"
        self.request_effect_choose_option = ["デッキの下に置く", "複写して手札に加える"]

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Spell | None, effect_choice: str | None):
        if selected_card_for_effect is not None and effect_choice is not None and selected_card_for_effect != self:
            player = game_state.current_player
            if effect_choice == "デッキの下に置く":
                selected_card_for_effect.mv(game_state.hands[player], mode="to_deck_bottom", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=player)
                if set_text:
                    the_actual_textbox.append_html_text(f"真実の宣告の効果で、プレイヤー{player}は手札の{selected_card_for_effect}をデッキの下に置いたのじゃ。\n")
            elif effect_choice == "複写して手札に加える":
                if len(game_state.hands[player]) < 9:
                    # Create a copy of the selected spell card
                    new_card_cls: Card = eval(f"{selected_card_for_effect.__class__.__name__}")
                    new_card = new_card_cls.cp(game_state, draw_ui, set_text, the_actual_textbox)
                    new_card.mv([new_card], mode="to_hand", game_state=game_state, draw_ui=draw_ui, set_text=set_text, the_actual_textbox=the_actual_textbox, player=player)
            else:
                raise ValueError("Invalid effect choice for 真実の宣告.")
        else:
            if set_text:
                the_actual_textbox.append_html_text("真実の宣告の効果は発動しなかったのじゃ。\n")


class 侮蔑の炎爪(Spell):
    """
    target value 8
    value: useful only in specific situations, average 6 points for damaging 3 opp followers
    total value: 6 points
    """
    def __init__(self):
        super().__init__(name="侮蔑の炎爪", cost=2)
        self.effect_description = "下記から1つの効果を選択し発動する。【1】場のすべてのフォロワーに1ダメージ。" \
        "【2】場のすべてのフォロワーに2ダメージ。"
        self.description = "捻り潰して千切り壊して、跡形も無く塵と灰！無様な有様ね世界共、私の下がお似合いよ！"
        self.request_effect_choose_option = ["1ダメージ", "2ダメージ"]

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        if effect_choice is not None:
            if effect_choice == "1ダメージ":
                damage_amount = 1
            elif effect_choice == "2ダメージ":
                damage_amount = 2
            else:
                raise ValueError("Invalid effect choice for 侮蔑の炎爪.")
            if set_text:
                the_actual_textbox.append_html_text(f"侮蔑の炎爪の効果で、場のすべてのフォロワーに{damage_amount}ダメージを与えるのじゃ。\n")
            for c in itertools.chain(game_state.fields[1].copy(), game_state.fields[2].copy()):
                if isinstance(c, Follower):
                    c.take_damage(damage_amount, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
        else:
            if set_text:
                the_actual_textbox.append_html_text("侮蔑の炎爪の効果は発動しなかったのじゃ。\n")


class 唯我の一刀(Spell):
    """
    Value: 5 damage * 3 = 15
    """
    def __init__(self):
        super().__init__(name="唯我の一刀", cost=4)
        self.effect_description = "自分のフェルトにフォロワー1体しかないとき、相手の場のフォロワーすべてに5ダメージ。"
        self.description = "己の神は己のみ。孤高こそ強さの証。"

    def on_play_effect(self, game_state, draw_ui, set_text, the_actual_textbox, selected_card_for_effect, effect_choice):
        if len(game_state.fields[game_state.current_player]) == 1:
            damage_amount = 5
            for c in game_state.fields[game_state.opponent].copy():
                if isinstance(c, Follower):
                    c.take_damage(damage_amount, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
        else:
            if set_text:
                the_actual_textbox.append_html_text("唯我の一刀の効果は発動しなかったのじゃ。\n")


class 簒奪の蛇剣(Spell):
    """
    Value: steal 1 card = 8 points
    """
    def __init__(self):
        super().__init__(name="簒奪の蛇剣", cost=2)
        self.effect_description = "相手の場のフォロワー1体を選び、それをXダメージ。Xは相手の手札の枚数である。" \
        "その後、相手の場がフォロワーでないなら、相手のリーダーにXダメージ。"
        self.request_card_selection_on_play = "field_opponent"

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Follower | None, effect_choice: str | None):
        player = game_state.current_player
        opponent = game_state.opponent
        x = len(game_state.hands[opponent])
        target = selected_card_for_effect
        if target is not None and isinstance(target, Follower):
            target.take_damage(x, game_state, draw_ui, set_text, the_actual_textbox, attacker=self)
        else:
            if set_text:
                the_actual_textbox.append_html_text("簒奪の蛇剣の効果は発動しなかったのじゃ。\n")
            return
        # Check if opponent has any followers left
        has_followers = any(isinstance(c, Follower) for c in game_state.fields[opponent])
        if not has_followers:
            game_state.player_take_damage(opponent, x, draw_ui, set_text)


class 円卓会議(Spell):
    """
    """
    def __init__(self):
        super().__init__(name="円卓会議", cost=3)
        self.effect_description = "下記の効果を1つ選び発動する。Xは自分の手札のフォロワーの数である。【1】" \
        "自分の場のフォロワーをすべて+0/+Xする。【2】自分の場のフォロワーをすべて+X/+0する。"
        self.request_effect_choose_option = ["+0/+X", "+X/+0"]

    def on_play_effect(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                        selected_card_for_effect: Card | None, effect_choice: str | None):
        player = game_state.current_player
        x = sum(1 for c in game_state.hands[player] if isinstance(c, Follower))
        if x == 0:
            if set_text:
                the_actual_textbox.append_html_text("円卓会議の効果は発動しなかったのじゃ。\n")
            return
        if effect_choice == "+0/+X":
            for c in game_state.fields[player]:
                if isinstance(c, Follower):
                    c.stats_change_effect(game_state, draw_ui, set_text, the_actual_textbox,
                                          imposter=self, attack_change=0, hp_change=x)
        elif effect_choice == "+X/+0":
            for c in game_state.fields[player]:
                if isinstance(c, Follower):
                    c.stats_change_effect(game_state, draw_ui, set_text, the_actual_textbox,
                                          imposter=self, attack_change=x, hp_change=0)
        else:
            raise ValueError("Invalid effect choice for 円卓会議.")


# ===============================
# Amulets
# ===============================

class 天界への階段(Amulet):
    """
    target value 8 points
    value: 6 heal 12 points but heal is heavily delayed. Also useless on full hp, different from damage.
    """
    def __init__(self):
        super().__init__(name="天界への階段", cost=2)
        self.effect_description = "魂カウンター5つを持つ。自分のフォロワーが場から破壊されたとき、これに魂カウンター1つを減らす。" \
        "魂カウンターがなくなったとき、それを破壊し、自分のリーダーをX回復する。Xは5-カウンターの数である。" \
        "カウンターの数0の場合、さらに1回復する。"
        self.counter_name = "魂カウンター"
        self.counter_max = 5
        self.counter = self.counter_max

    def effect_when_player_followers_destroyed(self, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox,
                                 destroyed_follower: Follower):
        for p in [1, 2]:
            if self in game_state.fields[p]:
                player_owning_this = p
                break
        if self.decrease_counter(1):
            self.destroy_amulet(game_state, draw_ui, set_text, the_actual_textbox, player_owning_this)

    def on_leave_field_effect(self, mode: str, game_state: SHCGGameState, draw_ui, set_text, the_actual_textbox, player: int):
        if mode == "destroy":
            heal = 5 - self.counter
            if self.counter == 0:
                heal += 1
            game_state.player_heal(player, heal, draw_ui, set_text)
            if set_text:
                the_actual_textbox.append_html_text(f"天界への階段の効果で、プレイヤー{player}は6回復したのじゃ。\n")
        

class 祈りの燭台(Amulet):
    """
    """
    def __init__(self):
        super().__init__(name="祈りの燭台", cost=5)
        self.description = "施しである。燃える火も、照らす日も、己が非すら、神の施し。――思慮深き御使いの福音、第三章十一行"
        self.effect_description = "エンドフェイズ開始時、カウンターは1減らし、自分のリーダーにX回復。" \
        "Xは自分の手札のフォロワーの数である。カウンターがなくなったとき、それを破壊する。"
        self.counter_name = "祈りの燭台カウンター"
        self.counter_max = 5
        self.counter = self.counter_max

    def end_of_turn_on_field_effect(self, game_state, draw_ui, set_text, the_actual_textbox):
        for p in [1, 2]:
            if self in game_state.fields[p]:
                player_owning_this = p
                break
        if self.decrease_counter(1):
            self.destroy_amulet(game_state, draw_ui, set_text, the_actual_textbox, player_owning_this)
        else:
            num_followers_in_hand = sum(1 for c in game_state.hands[player_owning_this] if isinstance(c, Follower))
            game_state.player_heal(player_owning_this, num_followers_in_hand, draw_ui, set_text)
            if set_text:
                the_actual_textbox.append_html_text(f"祈りの燭台の効果で、プレイヤー{player_owning_this}は{num_followers_in_hand}回復したのじゃ。\n")




# ==============================
# All Cards List
# ==============================

all_card_types: list[type[Card]] = [ゴブリン, ファイター, ゴリアテ, ガブリエル, ハンサ, 
                天なる大河, 唯我の絶傑マゼルベイン, ミヒライテ, フェアリーアサルト,
                機構翼の少女ローザ, 飢餓の使徒, 飢餓の輝き, 飢餓の絶傑ギルネリーゼ,
                不殺の絶傑エズディア, 真実の絶傑ライオ, 真実の宣告, 侮蔑の炎爪, 唯我の一刀, 侮蔑の絶傑ガルミーユ,
                神弓の座天使リリエル, 簒奪の絶傑オクトリス, 簒奪の蛇剣, オウルキャット, 円卓の騎士ガウェイン, 天界への階段,
                スターフェニックス, 白翼の守護神アイテール, 祈りの燭台, 神秘の指輪, キラキラヒーラー, ミスティアストロジスト,
                水竜神の巫女, 黄金都市の姫リテュエル, 癒しの奏者アンリエット, フレイルナイト, 円卓会議, お爺さんとお婆さん,
                ExampleCard]

# sort with follower spell amulet order, then by cost ascending, then by name alphabetical
_type_priority = {'follower': 0, 'spell': 1, 'amulet': 2}

def _card_sort_key(card_cls: type[Card]) -> tuple[int, int, str]:
    card = card_cls()  # instantiate to inspect metadata
    return (_type_priority[card.type], card.cost, card.name)

all_card_types.sort(key=_card_sort_key)